In [1]:
# Python ≥3.5 is required
import sys
assert sys.version_info >= (3, 5)
# Scikit-Learn ≥0.20 is required
import sklearn
assert sklearn.__version__ >= "0.20"

# Common imports
import numpy as np
import os

# To plot pretty figures
%matplotlib inline
import matplotlib as mpl
import matplotlib.pyplot as plt
mpl.rc('axes', labelsize=14)
mpl.rc('xtick', labelsize=12)
mpl.rc('ytick', labelsize=12)

# Where to save the figures
PROJECT_ROOT_DIR = "."
IMAGE_SUBFOLDER = "demo1"
IMAGES_PATH = os.path.join(PROJECT_ROOT_DIR, "images", IMAGE_SUBFOLDER)
os.makedirs(IMAGES_PATH, exist_ok=True)

Import dataset using pandas.

In [47]:
import pandas as pd
DATA_PATH = "./Dataset/truth_social"
def load_users_data(data_path=DATA_PATH):
    tsv_path = os.path.join(data_path, "users.tsv")
    return pd.read_table(tsv_path)
def load_follows_data(data_path=DATA_PATH):
    tsv_path = os.path.join(data_path, "follows.tsv")
    return pd.read_table(tsv_path)
def load_truths_data(data_path=DATA_PATH):
    tsv_path = os.path.join(data_path, "truths.tsv")
    return pd.read_table(tsv_path)
def load_quotes_data(data_path=DATA_PATH):
    tsv_path = os.path.join(data_path, "quotes.tsv")
    return pd.read_table(tsv_path)
def load_replies_data(data_path=DATA_PATH):
    tsv_path = os.path.join(data_path, "replies.tsv")
    return pd.read_table(tsv_path)
def load_media_data(data_path=DATA_PATH):
    tsv_path = os.path.join(data_path, "media.tsv")
    return pd.read_table(tsv_path)
def load_hashtags_data(data_path=DATA_PATH):
    tsv_path = os.path.join(data_path, "hashtags.tsv")
    return pd.read_table(tsv_path)
def load_externalurls_data(data_path=DATA_PATH):
    tsv_path = os.path.join(data_path, "externalurls.tsv")
    return pd.read_table(tsv_path)
def load_truthhashtagEdges_data(data_path=DATA_PATH):
    tsv_path = os.path.join(data_path, "truth_hashtag_edges.tsv")
    return pd.read_table(tsv_path)
def load_truthmediaEdges_data(data_path=DATA_PATH):
    tsv_path = os.path.join(data_path, "truth_media_edges.tsv")
    return pd.read_table(tsv_path)
def load_truthexturlEdges_data(data_path=DATA_PATH):
    tsv_path = os.path.join(data_path, "truth_external_url_edges.tsv")
    return pd.read_table(tsv_path)
def load_truthusertagEdges_data(data_path=DATA_PATH):
    tsv_path = os.path.join(data_path, "truth_user_tag_edges.tsv")
    return pd.read_table(tsv_path)

Data Cleaning:
Here let's first see the two important entities: users and truths

In [22]:
df_users = load_users_data()
df_users.head()

C:\Users\joe_c\AppData\Local\Temp\ipykernel_12440\4210485056.py:5: DtypeWarning: Columns (1,7,8,9) have mixed types. Specify dtype option on import or set low_memory=False.
  return pd.read_table(tsv_path)

,id,timestamp,time_scraped,username,follower_count,following_count,profile_url,finished_follower_scrape,finished_following_scrape,finished_truth_scrape
0,1238,2022-02-01 00:00:00,2022-09-19 14:43:26.11971,jeffgolfs,886,204,https://truthsocial.com/@jeffgolfs,f,f,f
1,50,2022-02-01 00:00:00,2022-09-15 02:01:38.652706,MizW,2365,2929,https://truthsocial.com/@MizW,f,f,f
2,6951,2022-02-01 00:00:00,2022-10-08 17:23:33.822145,SusanCreech,870,1232,https://truthsocial.com/@SusanCreech,f,f,f
3,9861,2022-02-01 00:00:00,2022-10-16 20:43:09.71727,BMF6FeeTDeeP,1086,1654,https://truthsocial.com/@BMF6FeeTDeeP,f,f,f
4,34,2022-02-01 00:00:00,2022-09-14 23:15:35.220658,DC_Draino,286146,81,https://truthsocial.com/@DC_Draino,t,t,t

The reason there are mixed types, is because there are some missing values that the author took care of it by assigning a -1 value to them.

In [23]:
df_users.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 454458 entries, 0 to 454457
Data columns (total 10 columns):
 #   Column                     Non-Null Count   Dtype
---  ------                     --------------   -----
 0   id                         454458 non-null  int64
 1   timestamp                  454458 non-null  object
 2   time_scraped               454458 non-null  object
 3   username                   454458 non-null  object
 4   follower_count             454458 non-null  int64
 5   following_count            454458 non-null  int64
 6   profile_url                454458 non-null  object
 7   finished_follower_scrape   454458 non-null  object
 8   finished_following_scrape  454458 non-null  object
 9   finished_truth_scrape      454458 non-null  object
dtypes: int64(3), object(7)
memory usage: 34.7+ MB

In [25]:
print(f'{df_users.groupby(df_users.columns[1] ).size()}\n\n')
print(f'{df_users.groupby(df_users.columns[2] ).size()}\n\n')
print(f'{df_users.groupby(df_users.columns[3] ).size()}\n\n')
print(f'{df_users.groupby(df_users.columns[4] ).size()}\n\n')
print(f'{df_users.groupby(df_users.columns[5] ).size()}\n\n')
print(f'{df_users.groupby(df_users.columns[6] ).size()}\n\n')
print(f'{df_users.groupby(df_users.columns[7] ).size()}\n\n')
print(f'{df_users.groupby(df_users.columns[8] ).size()}\n\n')
print(f'{df_users.groupby(df_users.columns[9] ).size()}\n\n')

timestamp
-1                     388922
-1                      43581
1969-12-01 00:00:00         2
2021-09-01 00:00:00         5
2021-12-01 00:00:00         3
2022-01-01 00:00:00         6
2022-02-01 00:00:00     16262
2022-03-01 00:00:00      1494
2022-04-01 00:00:00      1048
2022-05-01 00:00:00      2211
2022-06-01 00:00:00       481
2022-07-01 00:00:00       181
2022-08-01 00:00:00       162
2022-09-01 00:00:00        59
2022-10-01 00:00:00        34
2022-11-01 00:00:00         6
2022-12-01 00:00:00         1
dtype: int64


time_scraped
2022-09-04 23:14:03.216685    1
2022-09-04 23:32:44.771856    1
2022-09-04 23:32:57.045108    1
2022-09-04 23:34:48.061448    1
2022-09-04 23:48:55.819079    1
                             ..
2023-01-05 18:33:42.757360    1
2023-01-05 18:33:43.217965    1
2023-01-05 18:33:45.073850    1
2023-01-05 18:33:46.572249    1
2023-01-05 18:33:49.212789    1
Length: 454458, dtype: int64


username
-1               18
0                 1
00                1
000               1
0000              1
                 ..
zzzz              1
zzzz4u            4
zzzzyzx           1
zzzzz             1
zzzzzzzzzzzzz     1
Length: 454319, dtype: int64


follower_count
-1          432503
 0             587
 1              61
 2              67
 3              46
             ...
 1809193         1
 1955706         1
 2375491         1
 2524434         1
 4027829         1
Length: 8695, dtype: int64


following_count
-1        432503
 0           963
 1            94
 2           191
 3           106
           ...
 80633         1
 82711         1
 83756         1
 88242         1
 99514         1
Length: 7313, dtype: int64


profile_url
https://truthsocial.com/@0                1
https://truthsocial.com/@00               1
https://truthsocial.com/@000              1
https://truthsocial.com/@0000             1
https://truthsocial.com/@000000000000     1
                                         ..
https://truthsocial.com/@zzzz             1
https://truthsocial.com/@zzzz4u           4
https://truthsocial.com/@zzzzyzx          1
https://truthsocial.com/@zzzzz            1
https://truthsocial.com/@zzzzzzzzzzzzz    1
Length: 454316, dtype: int64


finished_follower_scrape
-1    388922
-1     43581
f      18240
t       3715
dtype: int64


finished_following_scrape
-1    388922
-1     43581
f      18531
t       3424
dtype: int64


finished_truth_scrape
-1    388922
-1     43581
f      18724
t       3231
dtype: int64

There are a lot of missing values -1 in finshed_follower_scrape and finished_following_scrape. 
Timestamp is the user account creation date. It has lots of missing values, and some accounts even consists the date "1969-12-01". It feels a bit odd. 
Usernames and Urls has the least missing values. 
The follower and following count has the most missing values with 432503. Thats 95% of the dataset! 
The dataset author mentioned that "Due to Truth Social's query limitations, not all users.tsv and truths.tsv data points were pulled directly from Truth Social." This might be the reason why some information was missing. I think we need to inspect the data but we don't necessarily need to exclude them because of missing data.

In [27]:
df_truths = load_truths_data()
df_truths.head()

,id,timestamp,time_scraped,is_retruth,is_reply,author,like_count,retruth_count,reply_count,text,external_id,url,truth_retruthed
0,703265,2022-05-14 00:00:00,2022-11-01 15:48:16.829245,t,f,2247,0,0,0,Q+ BE READY ANONS - PUBLIC AWAKENING COMING - ...,108351978111014587,https://truthsocial.com/@jweimer39/posts/10835...,1043583
1,807614,2022-03-27 00:00:00,2022-11-23 10:54:36.865046,t,f,20054,0,0,0,Enough is enough! RETRUTH,108040697775316106,https://truthsocial.com/@CeceBloomwood/posts/1...,988567
2,807615,2022-03-29 00:00:00,2022-11-23 10:55:11.613249,t,f,20054,0,0,0,https://justthenews.com/politics-policy/all-th...,108040478595657472,https://truthsocial.com/@CeceBloomwood/posts/1...,1002825
3,807618,2022-03-29 00:00:00,2022-11-23 10:56:29.134825,t,f,20054,0,0,0,https://t.me/realx22report/6729,108040420546204424,https://truthsocial.com/@CeceBloomwood/posts/1...,989757
4,807619,2022-03-29 00:00:00,2022-11-23 10:57:20.028953,f,t,20054,0,0,0,@CeceBloomwood,108040224733670356,https://truthsocial.com/@CeceBloomwood/posts/1...,-1

In [28]:
df_truths.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 845060 entries, 0 to 845059
Data columns (total 13 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   id               845060 non-null  int64
 1   timestamp        845060 non-null  object
 2   time_scraped     845060 non-null  object
 3   is_retruth       845060 non-null  object
 4   is_reply         845060 non-null  object
 5   author           845060 non-null  int64
 6   like_count       845060 non-null  int64
 7   retruth_count    845060 non-null  int64
 8   reply_count      845060 non-null  int64
 9   text             845060 non-null  object
 10  external_id      845060 non-null  int64
 11  url              845060 non-null  object
 12  truth_retruthed  845060 non-null  int64
dtypes: int64(7), object(6)
memory usage: 83.8+ MB

In [31]:
print(f'{df_truths.groupby(df_truths.columns[1] ).size()}\n\n')
print(f'{df_truths.groupby(df_truths.columns[2] ).size()}\n\n')
print(f'{df_truths.groupby(df_truths.columns[3] ).size()}\n\n')
print(f'{df_truths.groupby(df_truths.columns[4] ).size()}\n\n')
print(f'{df_truths.groupby(df_truths.columns[5] ).size()}\n\n')
print(f'{df_truths.groupby(df_truths.columns[6] ).size()}\n\n')
print(f'{df_truths.groupby(df_truths.columns[7] ).size()}\n\n')
print(f'{df_truths.groupby(df_truths.columns[8] ).size()}\n\n')
print(f'{df_truths.groupby(df_truths.columns[10] ).size()}\n\n')
print(f'{df_truths.groupby(df_truths.columns[11] ).size()}\n\n')
print(f'{df_truths.groupby(df_truths.columns[12] ).size()}\n\n')

timestamp
-1                     82356
2022-02-07 23:31:00        1
2022-02-08 16:22:00        1
2022-02-08 17:16:00        1
2022-02-08 17:22:00        2
                       ...
2022-10-14 23:54:00        2
2022-10-14 23:55:00        3
2022-10-14 23:57:00        1
2022-10-14 23:58:00        1
2022-10-14 23:59:00        1
Length: 213872, dtype: int64


time_scraped
2022-09-14 17:27:42.677694    1
2022-09-14 20:54:36.987914    1
2022-09-14 22:11:39.877727    1
2022-09-14 22:30:00.789046    1
2022-09-14 22:57:17.899789    1
                             ..
2023-01-05 12:37:57.416642    1
2023-01-05 12:37:57.437237    1
2023-01-05 12:37:57.443555    1
2023-01-05 12:37:57.447570    1
2023-01-05 12:37:57.450246    1
Length: 845060, dtype: int64


is_retruth
f    600854
t    244206
dtype: int64


is_reply
f    561869
t    283191
dtype: int64


author
22         79
23        451
24         89
25          1
26        102
         ...
445902      1
445906      1
445909      1
445910      1
445923      1
Length: 17377, dtype: int64


like_count
0         376299
1         132151
2          63298
3          35309
4          21533
           ...
109000         1
117000         1
131000         1
223000         1
268000         1
Length: 2322, dtype: int64


retruth_count
0        651729
1         22473
2         11507
3          7680
4          5808
          ...
33100         1
34300         1
38100         1
50100         1
51000         1
Length: 1898, dtype: int64


reply_count
0        579564
1         96878
2         31800
3         15372
4          9705
          ...
10100         1
21500         1
22900         1
26700         1
37500         1
Length: 1244, dtype: int64


external_id
107760498125955210    1
107764470573747444    1
107764685787231279    1
107764708370133894    1
107764708505688046    1
                     ..
109366535630009551    1
109377366616181916    1
109396528419492860    1
109398619876020855    2
109480454018636598    2
Length: 761607, dtype: int64


url
https://truthsocial.com/@002michi/posts/108444505118366327    1
https://truthsocial.com/@007ltk/posts/108371516406953136      1
https://truthsocial.com/@007ltk/posts/108375601871677371      1
https://truthsocial.com/@007ltk/posts/108379393214897889      1
https://truthsocial.com/@007ltk/posts/108391916155206865      1
                                                             ..
https://truthsocial.com/@zzzzyzx/posts/107864650727981146     1
https://truthsocial.com/@zzzzyzx/posts/107865018722633889     1
https://truthsocial.com/@zzzzyzx/posts/107865942870308659     1
https://truthsocial.com/@zzzzyzx/posts/107893976495214359     1
https://truthsocial.com/@zzzzyzx/posts/107935543411248378     1
Length: 845060, dtype: int64


truth_retruthed
-1          600864
 29             79
 37              2
 38              4
 40              3
             ...
 1060938         1
 1060939         1
 1060940         1
 1060941         1
 1060942         1
Length: 103302, dtype: int64

Here, only -1 in truth_retruth doesn't mean missing val, it means: this current truth is not a Retruth.

In [ ]:
# df_media = load_media_data()
# print(df_media.tail())
# print(df_media.info())
# print(f'{df_media.groupby(df_media.columns[1] ).size()}\n\n')

In [50]:
df_quote = load_quotes_data()
# print(df_quote.head())
print(df_quote.info())
# # print(f'{df_quote.groupby(df_quote.columns[1] ).size()}\n\n')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10508 entries, 0 to 10507
Data columns (total 7 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   id                        10508 non-null  int64
 1   timestamp                 10508 non-null  object
 2   time_scraped              10508 non-null  object
 3   quoted_user               10508 non-null  int64
 4   quoting_user              10508 non-null  int64
 5   quoting_truth             10508 non-null  int64
 6   quoted_truth_external_id  10508 non-null  int64
dtypes: int64(5), object(2)
memory usage: 574.8+ KB
None